-- Inserts
-- First, insert place categories
INSERT INTO place_categories (name, description) VALUES
('Historical Site', 'Places of historical significance including monuments, ruins, and museums'),
('Natural Wonder', 'Beautiful natural locations including parks, mountains, and beaches'),
('Cultural Venue', 'Places celebrating local culture, arts, and traditions'),
('Religious Site', 'Temples, churches, mosques, and other religious landmarks'),
('Entertainment', 'Modern entertainment venues and attractions'),
('Adventure Spot', 'Locations for extreme sports and outdoor activities'),
('Culinary Destination', 'Famous food markets, restaurant districts, and culinary experiences'),
('Shopping District', 'Popular shopping areas, markets, and retail destinations'),
('Science & Tech', 'Science museums, technology parks, and educational centers'),
('Beach Resort', 'Coastal destinations and beach attractions');


-- Insert countries
INSERT INTO countries (name, capital, currency, language, population, area, continent, flag_image) VALUES
('France', 'Paris', 'EUR', 'French', 67390000, 551695, 'EUROPE', 'france-flag.png'),
('Japan', 'Tokyo', 'JPY', 'Japanese', 125700000, 377975, 'ASIA', 'japan-flag.png'),
('Brazil', 'Brasília', 'BRL', 'Portuguese', 214300000, 8515770, 'AMERICA', 'brazil-flag.png'),
('Egypt', 'Cairo', 'EGP', 'Arabic', 104000000, 1001450, 'AFRICA', 'egypt-flag.png'),
('OCEANIA', 'Canberra', 'AUD', 'English', 25690000, 7692024, 'OCEANIA', 'OCEANIA-flag.png'),
('Italy', 'Rome', 'EUR', 'Italian', 60360000, 301340, 'EUROPE', 'italy-flag.png'),
('India', 'New Delhi', 'INR', 'Hindi', 1380000000, 3287263, 'ASIA', 'india-flag.png'),
('Mexico', 'Mexico City', 'MXN', 'Spanish', 128900000, 1964375, 'AMERICA', 'mexico-flag.png'),
('South Africa', 'Pretoria', 'ZAR', 'Multiple', 59308690, 1221037, 'AFRICA', 'south-africa-flag.png'),
('Thailand', 'Bangkok', 'THB', 'Thai', 69800000, 513120, 'ASIA', 'thailand-flag.png'),
('Spain', 'Madrid', 'EUR', 'Spanish', 47350000, 505990, 'EUROPE', 'spain-flag.png'),
('Canada', 'Ottawa', 'CAD', 'English/French', 38000000, 9984670, 'AMERICA', 'canada-flag.png'),
('Morocco', 'Rabat', 'MAD', 'Arabic', 37080000, 446550, 'AFRICA', 'morocco-flag.png');


-- Insert tourist places
INSERT INTO tourist_places (name, description, rating, image, opening_hours, price_range, country_id, category_id) VALUES
('Eiffel Tower', 'Iconic iron lattice tower on the Champ de Mars in Paris', 4.7, 'eiffel-tower.jpg', '09:00-00:00', '€€€',
    (SELECT id FROM countries WHERE name = 'France'),
    (SELECT id FROM place_categories WHERE name = 'Historical Site')),
('Mount Fuji', 'Japan''s highest mountain and most iconic natural symbol', 4.8, 'mount-fuji.jpg', '24/7', '€€',
    (SELECT id FROM countries WHERE name = 'Japan'),
    (SELECT id FROM place_categories WHERE name = 'Natural Wonder')),
('Christ the Redeemer', 'Art Deco statue of Jesus Christ in Rio de Janeiro', 4.6, 'christ-redeemer.jpg', '08:00-19:00', '€€',
    (SELECT id FROM countries WHERE name = 'Brazil'),
    (SELECT id FROM place_categories WHERE name = 'Religious Site')),
('Great Pyramid of Giza', 'Ancient Egyptian pyramid complex', 4.8, 'pyramid-giza.jpg', '08:00-17:00', '€€€',
    (SELECT id FROM countries WHERE name = 'Egypt'),
    (SELECT id FROM place_categories WHERE name = 'Historical Site')),
('Sydney Opera House', 'Multi-venue performing arts centre', 4.7, 'sydney-opera.jpg', '09:00-20:00', '€€€',
    (SELECT id FROM countries WHERE name = 'OCEANIA'),
    (SELECT id FROM place_categories WHERE name = 'Cultural Venue')),
('Colosseum', 'Ancient amphitheater in the heart of Rome', 4.7, 'colosseum.jpg', '08:30-19:00', '€€',
    (SELECT id FROM countries WHERE name = 'Italy'),
    (SELECT id FROM place_categories WHERE name = 'Historical Site')),
('Taj Mahal', 'Iconic marble mausoleum and UNESCO World Heritage site', 4.9, 'taj-mahal.jpg', '06:00-18:30', '€€',
    (SELECT id FROM countries WHERE name = 'India'),
    (SELECT id FROM place_categories WHERE name = 'Historical Site')),
('Chichen Itza', 'Ancient Maya city and pyramid', 4.8, 'chichen-itza.jpg', '08:00-17:00', '€€',
    (SELECT id FROM countries WHERE name = 'Mexico'),
    (SELECT id FROM place_categories WHERE name = 'Historical Site')),
('Kruger National Park', 'One of Africa''s largest game reserves', 4.9, 'kruger-park.jpg', '05:30-18:30', '€€€',
    (SELECT id FROM countries WHERE name = 'South Africa'),
    (SELECT id FROM place_categories WHERE name = 'Natural Wonder')),
('Grand Palace Bangkok', 'Former residence of Thai kings', 4.6, 'grand-palace.jpg', '08:30-15:30', '€€',
    (SELECT id FROM countries WHERE name = 'Thailand'),
    (SELECT id FROM place_categories WHERE name = 'Cultural Venue')),
('Sagrada Familia', 'Iconic basilica designed by Gaudi', 4.8, 'sagrada-familia.jpg', '09:00-18:00', '€€€',
    (SELECT id FROM countries WHERE name = 'Spain'),
    (SELECT id FROM place_categories WHERE name = 'Religious Site')),
('Banff National Park', 'Scenic mountain landscapes and wildlife', 4.9, 'banff.jpg', '24/7', '€€',
    (SELECT id FROM countries WHERE name = 'Canada'),
    (SELECT id FROM place_categories WHERE name = 'Natural Wonder')),
('Medina of Fez', 'Historic medieval city center', 4.7, 'fez-medina.jpg', '24/7', '€',
    (SELECT id FROM countries WHERE name = 'Morocco'),
    (SELECT id FROM place_categories WHERE name = 'Cultural Venue'));

-- Insert activities
INSERT INTO activities (name, description, price, duration, place_id) VALUES
('Eiffel Tower Summit Tour', 'Guided tour to the top of the Eiffel Tower with skip-the-line access', 74.99, '2 hours',
    (SELECT id FROM tourist_places WHERE name = 'Eiffel Tower')),
('Mount Fuji Climbing Tour', 'Guided climbing experience of Mount Fuji with experienced mountaineers', 199.99, '1 day',
    (SELECT id FROM tourist_places WHERE name = 'Mount Fuji')),
('Christ the Redeemer Scenic Tour', 'Guided tour with transportation and skip-the-line access', 49.99, '4 hours',
    (SELECT id FROM tourist_places WHERE name = 'Christ the Redeemer')),
('Pyramids Archaeological Tour', 'Expert-led tour of the Giza pyramid complex with historian', 89.99, '3 hours',
    (SELECT id FROM tourist_places WHERE name = 'Great Pyramid of Giza')),
('Sydney Opera House Backstage Tour', 'Early morning backstage tour of the Opera House', 159.99, '2 hours',
    (SELECT id FROM tourist_places WHERE name = 'Sydney Opera House')),
('Colosseum Underground Tour', 'Exclusive access to underground chambers and arena floor', 89.99, '3 hours',
    (SELECT id FROM tourist_places WHERE name = 'Colosseum')),
('Taj Mahal Sunrise Tour', 'Early morning tour with professional photographer', 79.99, '4 hours',
    (SELECT id FROM tourist_places WHERE name = 'Taj Mahal')),
('Chichen Itza Archaeological Tour', 'Expert-guided tour of Maya pyramids and temples', 69.99, '6 hours',
    (SELECT id FROM tourist_places WHERE name = 'Chichen Itza')),
('Kruger Safari Drive', 'Full-day game drive with experienced ranger', 199.99, '8 hours',
    (SELECT id FROM tourist_places WHERE name = 'Kruger National Park')),
('Grand Palace Walking Tour', 'Comprehensive tour of palace grounds and temples', 49.99, '4 hours',
    (SELECT id FROM tourist_places WHERE name = 'Grand Palace Bangkok')),
('Sagrada Familia Towers Access', 'Guided tour including tower access', 45.99, '2 hours',
    (SELECT id FROM tourist_places WHERE name = 'Sagrada Familia')),
('Banff Lake Louise Tour', 'Scenic tour of famous lakes and mountains', 129.99, '6 hours',
    (SELECT id FROM tourist_places WHERE name = 'Banff National Park')),
('Fez Medina Food Tour', 'Culinary walking tour of historic medina', 69.99, '4 hours',
    (SELECT id FROM tourist_places WHERE name = 'Medina of Fez')),
('Eiffel Tower Dinner Experience', 'Luxury dining at 58 Tour Eiffel restaurant', 199.99, '3 hours',
    (SELECT id FROM tourist_places WHERE name = 'Eiffel Tower')),
('Mount Fuji Photography Tour', 'Guided photography tour to the best viewpoints', 149.99, '6 hours',
    (SELECT id FROM tourist_places WHERE name = 'Mount Fuji')),
('Christ the Redeemer Sunset Tour', 'Special access during sunset hours with dinner', 89.99, '4 hours',
    (SELECT id FROM tourist_places WHERE name = 'Christ the Redeemer')),
('Pyramids Sound and Light Show', 'Evening show highlighting Egyptian history', 45.99, '2 hours',
    (SELECT id FROM tourist_places WHERE name = 'Great Pyramid of Giza')),
('Sydney Opera House Evening Performance', 'Premium seats for evening performance', 199.99, '3 hours',
    (SELECT id FROM tourist_places WHERE name = 'Sydney Opera House'));


-- Insert reviews
INSERT INTO reviews (ratings, comment, author, place_id) VALUES
(5.0, 'Absolutely breathtaking view of Paris! Worth every penny.', 'John Smith',
    (SELECT id FROM tourist_places WHERE name = 'Eiffel Tower')),
(4.8, 'A spiritual experience climbing Mount Fuji at sunrise.', 'Maria Garcia',
    (SELECT id FROM tourist_places WHERE name = 'Mount Fuji')),
(4.7, 'Incredible statue and even better views of Rio.', 'David Wilson',
    (SELECT id FROM tourist_places WHERE name = 'Christ the Redeemer')),
(5.0, 'Mind-blowing archaeological site. A must-see!', 'Ahmed Hassan',
    (SELECT id FROM tourist_places WHERE name = 'Great Pyramid of Giza')),
(4.9, 'The architecture is simply stunning. Amazing acoustics!', 'Emma Thompson',
    (SELECT id FROM tourist_places WHERE name = 'Sydney Opera House')),
(4.8, 'Walking through history! The underground tour was fascinating.', 'Laura Bennett',
    (SELECT id FROM tourist_places WHERE name = 'Colosseum')),
(5.0, 'Seeing the Taj Mahal at sunrise was a magical experience.', 'Raj Patel',
    (SELECT id FROM tourist_places WHERE name = 'Taj Mahal')),
(4.7, 'The astronomical precision of the Maya architecture is incredible.', 'Carlos Rodriguez',
    (SELECT id FROM tourist_places WHERE name = 'Chichen Itza')),
(5.0, 'Saw all Big Five in one day! Amazing experience.', 'Sophie Martin',
    (SELECT id FROM tourist_places WHERE name = 'Kruger National Park')),
(4.6, 'The intricate details of Thai architecture are stunning.', 'Lisa Chen',
    (SELECT id FROM tourist_places WHERE name = 'Grand Palace Bangkok')),
(4.9, 'Gaudi''s masterpiece is even more impressive in person.', 'Michael Brown',
    (SELECT id FROM tourist_places WHERE name = 'Sagrada Familia')),
(5.0, 'The most beautiful mountain scenery I''ve ever seen.', 'James Wilson',
    (SELECT id FROM tourist_places WHERE name = 'Banff National Park')),
(4.8, 'Getting lost in the medina was the highlight of our trip.', 'Hannah Lee',
    (SELECT id FROM tourist_places WHERE name = 'Medina of Fez')),
(4.9, 'The evening light makes the tower magical.', 'Elizabeth Taylor',
    (SELECT id FROM tourist_places WHERE name = 'Eiffel Tower')),
(4.7, 'Perfect weather for photography, amazing guide!', 'Yuki Tanaka',
    (SELECT id FROM tourist_places WHERE name = 'Mount Fuji')),
(4.8, 'The sunset view was worth every penny.', 'Pedro Santos',
    (SELECT id FROM tourist_places WHERE name = 'Christ the Redeemer')),
(4.6, 'The sound and light show was spectacular!', 'Omar Farooq',
    (SELECT id FROM tourist_places WHERE name = 'Great Pyramid of Giza')),
(5.0, 'World-class performance in a legendary venue.', 'Sarah Johnson',
    (SELECT id FROM tourist_places WHERE name = 'Sydney Opera House'));